vich_uploader:
    db_driver: orm

    mappings:
        test:
            uri_prefix: /images/tests/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/tests/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

